### ISSUE TITLE
Support copy/paste on MacOS

### ISSUE THREAD

**Issue by christophershirk** [danloh/mdSilo-app#203]
I would like to be able to use command-c, command-v for copy/paste on MacOS, and at least on my system, this isn't working (mdSilo version 0.4.1, Tauri 1.0.0, MacOS 13.0 Beta (22A5321d)).

This thread might be relevant:
https://github.com/tauri-apps/tauri/issues/849#issuecomment-918442151

Thank you for mdSilo!

**Comment by danloh** [comment]
I think command-c/command-v works well on Mac now (v0.4.3).

**Comment by christophershirk** [comment]
Confirmed, thank you very much.
