### ISSUE TITLE
Relative paths to images and files

### ISSUE THREAD

**Issue by amiyatulu** [danloh/mdSilo-app#258]
Images are stored as absolute path, this can be problematic for backup purposes.

``` ![](asset://%2Fhome%2Famiya%2FDocuments%2Fmdsilo%2FRust%2Fmdsilo.png)```

Images are not rendered with relative paths when keeping the `.png` file on same folder that of `.md` file
```![](mdsilo.png)```

Thank you for making the wonderful app. Seems this is the only main additional feature I need to make it my primary note taking app.

**Comment by amiyatulu** [comment]
Sorry, this feature is available on the setting.

**Comment by danloh** [comment]
Tips: better relative path (`./`) support shipped in v0.4.7:  https://mdsilo.com/
