### ISSUE TITLE
Creating a new code block after the next line converts the previous line into code block

### ISSUE THREAD

**Issue by amiyatulu** [danloh/mdSilo-app#283]
Creating a new code block after the next line converts the previous line into code block, instead of code block in the new line 

![line](https://user-images.githubusercontent.com/2051004/196421070-363c3778-3f0a-4f94-8e33-c02b94cdb328.png)
![output](https://user-images.githubusercontent.com/2051004/196421105-b53bb8ab-8c04-497c-9e72-ca4218e936d0.png)

- mdSilo Version: 0.4.8

**Comment by danloh** [comment]
Thanks for your feedback. need to investigate this issue. 

I found it also converts the below line to block, not only on code block, also on list, quote block, etc.  

Stopgap measures: 
- use shortcuts  to create block: ```` ``` ````, `>`, `- `, `[]`, ... 
- to reserve new line above and below the block when using slash command

**Comment by danloh** [comment]
fixed: https://github.com/danloh/mdSilo-app/releases/tag/app-v0.4.9
