### ISSUE TITLE
hide markdown title in mind map view

### ISSUE THREAD

**Issue by hwy1782** [danloh/mdSilo-app#285]
**Is your feature request related to a problem? Please describe.**
The markdown file  title in the mind map view takes up too much space, affecting viewing.

**Describe the solution you'd like**
hide markdown title in mind map view

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/2442046/197384924-bf078874-bc99-4f82-81be-a6532b546f78.png)

**Comment by danloh** [comment]
Ok, maybe can add a full-screen button? 

**Stopgap measure** :  zoom-in/out and move to view

**Comment by hwy1782** [comment]
It would be even better if there was a fullscreen button

**Comment by danloh** [comment]
Now can view mindmap in full-screen on web app:  top-right 3-dot drop-down -> MindMap Preview

BTW, Please open issue about web app here:  https://github.com/danloh/mdSilo-web/issues/new/choose
