### ISSUE TITLE
Pasting text does not work properly on MacOS

### ISSUE THREAD

**Issue by errorsandwarnings** [danloh/mdSilo-app#305]
**Describe the bug**
Trying to copy and paste text from another source to mdSilo is not working correctly all the time.

**To Reproduce**
Make new notes, copy paste text using keyboard shortcut or UI, it does not work in both cases

**Expected behavior**
 I expect it to work consistently. This is a basic functionality

**Screenshots**
NA

**Desktop (please complete the following information):**

- OS Version 
- Checked on following 
- MacOS Catalina ( Intel )
- MacOS Monterey ( M1 )
-
- mdSilo version
0.5.1
0.5.0

**Additional context**

**Comment by danloh** [comment]
There is a regression on cmd-c / cmd-v (macOS, app: 0.5, Tauri: 1.2), 
ref: https://github.com/tauri-apps/tauri/issues/5669

**Comment by danloh** [comment]
now cmd-c/v works on Mac again(v0.5.2):  https://github.com/danloh/mdSilo-app/releases/tag/app-v0.5.2
