### ISSUE TITLE
Table management is not accessible when only one column remains

### ISSUE THREAD

**Issue by errorsandwarnings** [danloh/mdSilo-app#306]
**Describe the bug**
A single column table would not display the UI to add/remove rows and columns anymore

**To Reproduce**
Create a table
Remove columns until you are left with a single column.
Try to add columns or rows.

**Expected behavior**
Table management should be accessible in all situations

**Screenshots**
NA

**Desktop (please complete the following information):**

- MacOS Monterey - M1 chip
- mdSilo version - 0.5.1

**Additional context**

**Comment by danloh** [comment]
stopgap: can press `Enter` to add row,  but to add col is a problem in this case.

**Comment by danloh** [comment]
fixed on v0.5.2: https://github.com/danloh/mdSilo-app/releases/tag/app-v0.5.2
