### ISSUE TITLE
Link not displaying correctly - Auto Changes into NaN problem

### ISSUE THREAD

**Issue by errorsandwarnings** [danloh/mdSilo-app#325]
**Describe the bug**
I added few links into notes. One of those automatically converts to NaN. The markdown has been edited multiple times. There is some funny behavior here.

**To Reproduce**
Open the associated ML.md into mdSilo and hope it would reproduce. You can also check the screenshots and associated mdSilo export.

**Expected behavior**
This should display links properly like the ones on top.

**Screenshots**
![Screenshot 2022-12-11 at 6 54 54 PM](https://user-images.githubusercontent.com/37195748/206936363-4ce38559-0d72-4d21-845c-a5849079f307.png)
![Screenshot 2022-12-11 at 6 54 44 PM](https://user-images.githubusercontent.com/37195748/206936366-70389d1a-2f10-43db-934d-4495e871f972.png)
[ML.md](https://github.com/danloh/mdSilo-app/files/10203599/ML.md)

**Desktop (please complete the following information):**

- macOS Catalina 10.15.7 
- mdSilo - 0.5.2

**Comment by danloh** [comment]
fixed
